Add async proxy api
janbrummer/libproxy2 pull request #22
Opened 2023-01-30 10:45 UTC by janbrummer

2023-01-30 14:26 UTC, DimStar77 commented on src/libproxy/proxy.h
> +void px_proxy_factory_get_proxies_async (pxProxyFactory *self, const char *url, pxProxyCallback callback, void *data);
New public API, needs to be added to the libproxy.map

2023-01-30 15:07 UTC, janbrummer commented on src/libproxy/proxy.h
> +void px_proxy_factory_get_proxies_async (pxProxyFactory *self, const char *url, pxProxyCallback callback, void *data);
Never used them before. Adding them there and increase patch version?

2023-01-30 15:14 UTC, DimStar77 commented on src/libproxy/proxy.h
> +void px_proxy_factory_get_proxies_async (pxProxyFactory *self, const char *url, pxProxyCallback callback, void *data);
should be something like this:

```
--git a/src/libproxy/libproxy.map b/src/libproxy/libproxy.map
index 32f0db3..3577c66 100644
--- a/src/libproxy/libproxy.map
+++ b/src/libproxy/libproxy.map
@@ -6,3 +6,9 @@ LIBPROXY_0.4.16 {
     px_proxy_factory_free;
 };
 
+LIBPROXY_0.5 {
+  global:
+    px_proxy_factory_get_proxies_async;
+
+} LIBPROXY_0.4.16;
+
```

introduce the new symbol version LIBPROXY_0.5, declare px_proxy_factory_get_proxies_async as publically available since this version. And make that version to be a followup (thus inheriting the symbols) to LIBPROXY_0.4.16

This results in declaring px_proxy_factory_get_proxies_async@LIBPROXY_0.5 to be added to the symbol table. (it gets especially interesting with auto rpm deps here)

2023-01-30 15:24 UTC, janbrummer commented
@mcatanzaro Is this fine for you?

2023-01-30 15:25 UTC, DimStar77 commented on src/libproxy/libproxy.map
> +    px_proxy_factory_get_proxies_async;
Only add the new symbol to 0.5; it did not exist in 0.4.16

2023-01-30 15:29 UTC, janbrummer commented on src/libproxy/libproxy.map
> +    px_proxy_factory_get_proxies_async;
Gnarf.. fine :)

2023-01-30 15:29 UTC, janbrummer commented on src/libproxy/libproxy.map
> +};
Had to switch the order, now it's fine. Thanks  o/

2023-01-30 15:31 UTC, DimStar77 commented on src/libproxy/libproxy.map
> +};
now the diff is pretty much in line with what I posted :) Seems ok now

2023-01-30 16:29 UTC, mcatanzaro requested changes
Tangent: I'm really not sure about the symbol versioning. I've never attempted to use that before, and I don't understand how it works. I'm not sure whether adding symbol versioning where it didn't exist in the past is backwards-compatible or not. In particular, I'm not sure whether this is useful if you do not plan to maintain multiple versions of the same API function. Maybe it's fine, but nothing in GNOME uses symbol versioning afaik, so I have no experience with it. Just want to make sure you understand it's not very typical.

2023-01-30 16:29 UTC, mcatanzaro commented on src/libproxy/proxy.c
> +}
Instead of letting the call run forever without completing, I would complete it here with some sort of error. However, this API doesn't provide any way to indicate an error, so got to think about how to do that....

2023-01-30 16:29 UTC, mcatanzaro commented on src/libproxy/proxy.h
> +void px_proxy_factory_get_proxies_async (pxProxyFactory *self, const char *url, pxProxyCallback callback, void *data);
I'm nervous that there's no way to cancel the async function call. This means the caller needs to manually guarantee that px_proxy_factory_free() is not called until after the callback executes. That seems extremely error-prone. With GLib in the public API, this would be as easy as adding a GCancellable parameter, but you clearly don't want to add GLib to the public API. Another solution would be to add refcounting to pxProxyFactory so that the caller can unref when it's no longer needed while the callback keeps a ref alive. Opinions?

2023-01-30 16:29 UTC, mcatanzaro commented on src/libproxy/proxy-dbus.c
> +  struct GetProxiesData *proxies_data = g_malloc0 (sizeof (struct GetProxiesData));
This works, but you can also use g_new0.

2023-01-30 16:29 UTC, mcatanzaro commented on src/libproxy/proxy-dbus.c
> +  g_autoptr (GVariant) result = g_dbus_proxy_call_finish (G_DBUS_PROXY (source_object), res, &error);
You never check error... should print a g_warning() if `!g_error_matches (error, G_IO_ERROR, G_IO_ERROR_CANCELLED`

2023-01-30 16:29 UTC, mcatanzaro commented on src/backend/px-manager.h
> +                                    GError     **error);
```suggestion
void px_manager_get_proxies_async (PxManager   *self,
                                   const char  *url,
                                   GError     **error);
```

2023-01-30 16:35 UTC, janbrummer commented
> Tangent: I'm really not sure about the symbol versioning. I've never attempted to use that before, and I don't understand how it works. I'm not sure whether adding symbol versioning where it didn't exist in the past is backwards-compatible or not. In particular, I'm not sure whether this is useful if you do not plan to maintain multiple versions of the same API function. Maybe it's fine, but nothing in GNOME uses symbol versioning afaik, so I have no experience with it. Just want to make sure you understand it's not very typical.

Totally new for me as well. Never used it. But I'm fine if @DimStar77 request it.

2023-01-30 16:36 UTC, janbrummer commented on src/libproxy/proxy.h
> +void px_proxy_factory_get_proxies_async (pxProxyFactory *self, const char *url, pxProxyCallback callback, void *data);
We talked about this and the first ideas was to add another async header file with an additional pkg conf file, to expose glib api. But I'm not sure whether we would force other projects into glib then. Don't know..

2023-01-30 16:36 UTC, mcatanzaro commented on src/libproxy/proxy.c
> +}
Well, maybe it's not actually useful to have if it's not guaranteed to be implemented....

2023-01-30 16:39 UTC, mcatanzaro commented on src/libproxy/proxy.h
> +void px_proxy_factory_get_proxies_async (pxProxyFactory *self, const char *url, pxProxyCallback callback, void *data);
Actually, the call will just hang if the caller is not iterating the default GMainContext, so... we'll have to document that the application must use GLib no matter what. :/ Are you OK with that?

If you don't like the GLib requirement, then... well, having a sync-only library API is really bad, but it might be OK if we tell people the library API is deprecated and provided only for backwards-compat, and always use D-Bus instead? Just brainstorming.

2023-01-30 16:40 UTC, DimStar77 commented
> Tangent: I'm really not sure about the symbol versioning. I've never attempted to use that before, and I don't understand how it works. I'm not sure whether adding symbol versioning where it didn't exist in the past is backwards-compatible or not. In particular, I'm not sure whether this is useful if you do not plan to maintain multiple versions of the same API function. Maybe it's fine, but nothing in GNOME uses symbol versioning afaik, so I have no experience with it. Just want to make sure you understand it's not very typical.

* Libproxy 0.4.16 already had versioned symbols; not adding the versioned symbols back would be an ABI break
* Adding them does not break ABI (it's added to the elf header as @@, denoting the default, used when not versioned symols are used)

The main advantage, unless we ever need to do backward compat ABI, is for rpm distros to have a chance to declare that a binary might need the new ABI symbol, even with the soname still being libproxy.so.1

Otherwise all consumers of libproxy.so.1 have no indication if they need a newer version than 0.4.16 or if 0.4.16 is fine (rpm creates auto-deps based on that info, so any code built that does not use async will get a dep to LIBPROXY_0.4.16, the one using asynx gets LIBPROXY_0.5); GNOME not doing it is a constant pain and not an excuse not to do it IMHO

2023-01-30 16:43 UTC, mcatanzaro commented on src/libproxy/proxy-dbus.c
> +  proxies_data->user_data = data;
You should also explicitly track the GMainContext to use for the operation. Use g_main_context_ref_thread_default() and store it in the GetProxiesData. Currently, the callback is already guaranteed to be called on this main context (the main context that is thread-default at the time that px_proxy_factory_get_proxies_async() is called) because that's what g_dbus_proxy_call() says will happen, so it's good currently, but explicit is better than implicit. Then you can invoke the callback at the bottom of on_proxy_ready() using g_main_context_invoke().

2023-01-30 16:44 UTC, janbrummer commented on src/libproxy/proxy.h
> +void px_proxy_factory_get_proxies_async (pxProxyFactory *self, const char *url, pxProxyCallback callback, void *data);
This will not work, as dbus interface is not working on all systems and i'd still love to use those with proxies. So we need the lib to hide the non/dbus api.

Regarding backwards compatibility i wouldn't add them here. So either a new header/pc or bump major number and add the dependency. What about curl then?

2023-01-30 16:49 UTC, janbrummer commented on src/libproxy/proxy.c
> +}
That's just TODO and an offer for you to help designing the API for your needs :)

2023-01-30 16:59 UTC, mcatanzaro commented
> Libproxy 0.4.16 already had versioned symbols; not adding the versioned symbols back would be an ABI break

Oh, OK then.

BTW you might be interested in https://github.com/rpm-software-management/rpm/pull/2372

2023-01-30 17:38 UTC, mcatanzaro commented on src/libproxy/proxy.h
> +void px_proxy_factory_get_proxies_async (pxProxyFactory *self, const char *url, pxProxyCallback callback, void *data);
Maybe we could do:

 * proxy.h: deprecated, backwards-compatible API, sync-only
 * New header: new API that requires GLib, includes async functions and future hooks for curl

?

2023-01-30 17:44 UTC, DimStar77 commented on src/libproxy/proxy.h
> +void px_proxy_factory_get_proxies_async (pxProxyFactory *self, const char *url, pxProxyCallback callback, void *data);
I don't see the proxy.h use as deprecated. But I don't object to a 2nd header (and possibly 2nd .pc file for consumers to pick from to get the correct build flags

libproxy gained a gio-2.0 dep already for the dbus calls. Consumers of that lib all will get glib/gio already )

2023-01-30 17:56 UTC, mcatanzaro commented on src/libproxy/proxy.h
> +void px_proxy_factory_get_proxies_async (pxProxyFactory *self, const char *url, pxProxyCallback callback, void *data);
The problem is those calls will never complete if the app is not running a GMainContext, which is unclear.

2023-02-02 15:33 UTC, mcatanzaro commented
I think I was wrong to suggest a generic async API would be possible. Problem is this requires event loop integration, which I failed to consider. What you have now works only for GLib applications. Solutions: (a) move this to a GLib-specific header (will we have a Qt header as well, then?), or (b) add APIs to integrate event loops (complicated, surely overkill), or (c) tell people to just use D-Bus (seems like the right answer for Linux at least), or (d) tell people to use the current sync APIs only on a secondary thread (difficult, dangerous).

You actually have the same problem in the D-Bus code currently. If the application is not iterating a GMainContext, the D-Bus calls will just never finish.

2023-02-02 15:52 UTC, janbrummer commented
I tend to move to a libproxy-glib for async functionality. D-Bus actually works quiet fine with those sync calls.

I do have a more significatn problem with dbus at the moment...

2023-02-07 09:57 UTC, janbrummer commented on src/libproxy/proxy.c
> +}
Outdated.

2023-02-07 09:58 UTC, janbrummer commented on src/libproxy/proxy.h
> +void px_proxy_factory_get_proxies_async (pxProxyFactory *self, const char *url, pxProxyCallback callback, void *data);
Outdated. Added proxy-glib.

2023-02-08 21:42 UTC, mcatanzaro requested changes
OK, now this API looks good. I like the approach of adding the APIs in a separate -glib header because that makes it pretty clear that you should not attempt to use the async API unless you're iterating a GMainContext.

2023-02-08 21:42 UTC, mcatanzaro commented on src/libproxy/proxy-glib.c
> +  char **ret = px_proxy_factory_get_proxies (self, uri);
But surely px_proxy_factory_get_proxies() is not threadsafe? There is no locking at all, so surely it cannot be used except on the thread that it was created on. And I don't think adding locking is advisable either. Using multiple threads gets very complicated and dangerous.

Better to change px-manager to be async throughout. The synchronous API calls can create a GMainContext, push thread default, iterate it until the operation has completed, then pop thread default.

2023-02-08 21:42 UTC, mcatanzaro commented on src/libproxy/proxy-glib.c
> +  g_task_set_return_on_cancel (task, TRUE);
Problem is the thread function does not comply with the requirements of g_task_set_return_on_cancel():

> To do that, the thread should call g_task_set_return_on_cancel() again to (atomically) set return-on-cancel FALSE before making externally-visible changes; if the task gets cancelled before the return-on-cancel flag could be changed, g_task_set_return_on_cancel() will indicate this by returning FALSE.

2023-02-08 21:45 UTC, mcatanzaro commented on src/libproxy/proxy-glib.h
> +#pragma once
I recommend not using `#pragma once` in the public header files proxy.h and proxy-glib.h simply because it is nonstandard and will be exposed to applications, so theoretically this could limit your choice of compilers when building applications that depend on libproxy. (Of course it's fine in all the other headers.)

2023-02-08 21:45 UTC, mcatanzaro commented on src/libproxy/proxy-glib.h
> +#endif
Careful, this should be _after_ you #include everything.

(Also, since this is a GLib-specific header, you could optionally use `G_BEGIN_DECLS` and `G_END_DECLS` instead. Or not, for consistency with proxy.h. Doesn't matter.)

2023-02-08 23:23 UTC, mcatanzaro commented
Another issue is: Daniel is going to want curl to use this async API (he was pretty clear in https://github.com/curl/curl/pull/9068#issuecomment-1225748793 that sync API is not acceptable), but I highly doubt curl iterates a GMainContext, so this won't work for curl. I have no clue what else to do, though. Adding API to allow use of arbitrary event loop would be more complex than the rest of libproxy's APIs combined. Without an event loop, there's no way to ever execute the async callback, so an event loop is kind of inherently required for an async API. It might be time to show this to Daniel and see if he has suggestions?

2023-02-09 15:36 UTC, mcatanzaro commented
Actually there's an even bigger problem here: almost nobody would ever want to use this GLib-style async API, because GProxyResolver exists, and that is already a wrapper around libproxy with async API. If you're using GLib anyway, you should surely use that rather than using libproxy directly. So this async API would only really be needed by glib-networking, to implement the GProxyResolver. But glib-networking could simply use the D-Bus API instead.

So yeah, I think it's not worth it to try to salvage this GLib-style async API. I think it's time to ping Daniel and ask him what he'd like to see for curl's purposes.

2023-02-09 15:37 UTC, mcatanzaro commented
> I think it's time to ping Daniel and ask him what he'd like to see for curl's purposes.

Oh, I see you just did, 11 minutes ago. Great.

2023-03-09 16:35 UTC, janbrummer commented
FTR: We will go for the glib async api in the first run. If there is still the need for something else we can do it later.

2023-03-09 17:18 UTC, mcatanzaro commented
I don't think you should. Like I said, nobody would ever use this API. If you're using GLib you might as well just use g_proxy_resolver_lookup_async().

2023-03-09 17:18 UTC, closed without merging